services:
  notion-finance:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    container_name: notion-finance
    ports:
      - "100.121.234.22:8501:8501"
    restart: always
    volumes:
      - ~/.streamlit:/root/.streamlit
